# Day17 : ANN

In [15]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [16]:
tf.__version__

'2.9.1'

In [17]:
dataset = pd.read_csv('D:/Churn_Modelling.csv')
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [18]:
dataset.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [19]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [20]:
# Encoding : Gender
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [21]:
X[2]

array([502, 'France', 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
      dtype=object)

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [23]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [25]:
#Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [26]:
#ANN
#Initializing the ANN
ann = tf.keras.models.Sequential()

In [29]:
#Adding input layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
#Adding second layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [30]:
#Adding output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [31]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [32]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 781us/step - loss: 0.6604 - accuracy: 0.6230
Epoch 2/100
250/250 [==============================] - 0s 897us/step - loss: 0.5037 - accuracy: 0.7924
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4549 - accuracy: 0.8102
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4334 - accuracy: 0.8129
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4213 - accuracy: 0.8149
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4124 - accuracy: 0.8183
Epoch 7/100
250/250 [==============================] - 0s 797us/step - loss: 0.4049 - accuracy: 0.8231
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3982 - accuracy: 0.8260
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3920 - accuracy: 0.8315
Epoch 10/100
250/250 [==============================] - 0s 834us/step - loss: 0.3860 - accuracy: 0.8369
Epoch 11/100
250/250 [==============================] - 0s 741us/step - loss: 0.3803 - accuracy: 0.8401
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3753 - accuracy: 0.8444
Epoch 13/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3704 - accuracy: 0.8469
Epoch 14/100
250/250 [==============================] - 0s 817us/step - loss: 0.3660 - accuracy: 0.8497
Epoch 15/100
250/250 [==============================] - 0s 837us/step - loss: 0.3624 - accuracy: 0.8515
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3593 - accuracy: 0.8524
Epoch 17/100
250/250 [==============================] - 0s 769us/step - loss: 0.3566 - accuracy: 0.8547
Epoch 18/100
250/250 [==============================] - 0s 904us/step - loss: 0.3544 - accuracy: 0.8536
Epoch 19/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3527 - accuracy: 0.8556
Epoch 20/100
250/250 [==============================] - 0s 741us/step - loss: 0.3512 - accuracy: 0.8560
Epoch 21/100
250/250 [==============================] - 0s 701us/step - loss: 0.3501 - accuracy: 0.8556
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3490 - accuracy: 0.8561
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3483 - accuracy: 0.8565
Epoch 24/100
250/250 [==============================] - 0s 897us/step - loss: 0.3474 - accuracy: 0.8561
Epoch 25/100
250/250 [==============================] - 0s 784us/step - loss: 0.3466 - accuracy: 0.8565
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3460 - accuracy: 0.8571
Epoch 27/100
250/250 [==============================] - 0s 785us/step - loss: 0.3453 - accuracy: 0.8583
Epoch 28/100
250/250 [==============================] - 0s 709us/step - loss: 0.3450 - accuracy: 0.8584
Epoch 29/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3446 - accuracy: 0.8579
Epoch 30/100
250/250 [==============================] - 0s 769us/step - loss: 0.3440 - accuracy: 0.8591
Epoch 31/100
250/250 [==============================] - 0s 697us/step - loss: 0.3435 - accuracy: 0.8605
Epoch 32/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3431 - accuracy: 0.8591
Epoch 33/100
250/250 [==============================] - 0s 901us/step - loss: 0.3427 - accuracy: 0.8585
Epoch 34/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3424 - accuracy: 0.8599
Epoch 35/100
250/250 [==============================] - 0s 813us/step - loss: 0.3421 - accuracy: 0.8593
Epoch 36/100
250/250 [==============================] - 0s 747us/step - loss: 0.3418 - accuracy: 0.8606
Epoch 37/100
250/250 [==============================] - 0s 633us/step - loss: 0.3414 - accuracy: 0.8591
Epoch 38/100
250/250 [==============================] - 0s 605us/step - loss: 0.3413 - accuracy: 0.8602
Epoch 39/100
250/250 [==============================] - 0s 609us/step - loss: 0.3410 - accuracy: 0.8591
Epoch 40/100
250/250 [==============================] - 0s 661us/step - loss: 0.3408 - accuracy: 0.8611
Epoch 41/100
250/250 [==============================] - 0s 657us/step - loss: 0.3408 - accuracy: 0.8605
Epoch 42/100
250/250 [==============================] - 0s 625us/step - loss: 0.3403 - accuracy: 0.8606
Epoch 43/100
250/250 [==============================] - 0s 876us/step - loss: 0.3402 - accuracy: 0.8596
Epoch 44/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3401 - accuracy: 0.8614
Epoch 45/100
250/250 [==============================] - 0s 685us/step - loss: 0.3401 - accuracy: 0.8597
Epoch 46/100
250/250 [==============================] - 0s 757us/step - loss: 0.3401 - accuracy: 0.8605
Epoch 47/100
250/250 [==============================] - 0s 773us/step - loss: 0.3399 - accuracy: 0.8616
Epoch 48/100
250/250 [==============================] - 0s 873us/step - loss: 0.3395 - accuracy: 0.8600
Epoch 49/100
250/250 [==============================] - 0s 806us/step - loss: 0.3398 - accuracy: 0.8608
Epoch 50/100
250/250 [==============================] - 0s 721us/step - loss: 0.3396 - accuracy: 0.8609
Epoch 51/100
250/250 [==============================] - 0s 889us/step - loss: 0.3396 - accuracy: 0.8616
Epoch 52/100
250/250 [==============================] - 0s 999us/step - loss: 0.3396 - accuracy: 0.8624
Epoch 53/100
250/250 [==============================] - 0s 913us/step - loss: 0.3395 - accuracy: 0.8619
Epoch 54/100
250/250 [==============================] - 0s 825us/step - loss: 0.3393 - accuracy: 0.8609
Epoch 55/100
250/250 [==============================] - 0s 825us/step - loss: 0.3391 - accuracy: 0.8620
Epoch 56/100
250/250 [==============================] - 0s 821us/step - loss: 0.3393 - accuracy: 0.8621
Epoch 57/100
250/250 [==============================] - 0s 919us/step - loss: 0.3391 - accuracy: 0.8635
Epoch 58/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3392 - accuracy: 0.8606
Epoch 59/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3391 - accuracy: 0.8627
Epoch 60/100
250/250 [==============================] - 0s 887us/step - loss: 0.3390 - accuracy: 0.8614
Epoch 61/100
250/250 [==============================] - 0s 953us/step - loss: 0.3391 - accuracy: 0.8615
Epoch 62/100
250/250 [==============================] - 0s 829us/step - loss: 0.3390 - accuracy: 0.8609
Epoch 63/100
250/250 [==============================] - 0s 813us/step - loss: 0.3389 - accuracy: 0.8625
Epoch 64/100
250/250 [==============================] - 0s 733us/step - loss: 0.3389 - accuracy: 0.8615
Epoch 65/100
250/250 [==============================] - 0s 831us/step - loss: 0.3387 - accuracy: 0.8620
Epoch 66/100
250/250 [==============================] - 0s 751us/step - loss: 0.3387 - accuracy: 0.8614
Epoch 67/100
250/250 [==============================] - 0s 717us/step - loss: 0.3387 - accuracy: 0.8612
Epoch 68/100
250/250 [==============================] - 0s 773us/step - loss: 0.3386 - accuracy: 0.8620
Epoch 69/100
250/250 [==============================] - 0s 657us/step - loss: 0.3385 - accuracy: 0.8616
Epoch 70/100
250/250 [==============================] - 0s 721us/step - loss: 0.3385 - accuracy: 0.8615
Epoch 71/100
250/250 [==============================] - 0s 661us/step - loss: 0.3386 - accuracy: 0.8636
Epoch 72/100
250/250 [==============================] - 0s 601us/step - loss: 0.3383 - accuracy: 0.8619
Epoch 73/100
250/250 [==============================] - 0s 724us/step - loss: 0.3384 - accuracy: 0.8618
Epoch 74/100
250/250 [==============================] - 0s 931us/step - loss: 0.3385 - accuracy: 0.8624
Epoch 75/100
250/250 [==============================] - 0s 751us/step - loss: 0.3383 - accuracy: 0.8625
Epoch 76/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3382 - accuracy: 0.8622
Epoch 77/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3382 - accuracy: 0.8622
Epoch 78/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3382 - accuracy: 0.8624
Epoch 79/100
250/250 [==============================] - 0s 809us/step - loss: 0.3382 - accuracy: 0.8622
Epoch 80/100

250/250 [==============================] - 0s 669us/step - loss: 0.3382 - accuracy: 0.8625
Epoch 81/100
250/250 [==============================] - 0s 649us/step - loss: 0.3380 - accuracy: 0.8619
Epoch 82/100
250/250 [==============================] - 0s 645us/step - loss: 0.3381 - accuracy: 0.8622
Epoch 83/100
250/250 [==============================] - 0s 655us/step - loss: 0.3380 - accuracy: 0.8616
Epoch 84/100
250/250 [==============================] - 0s 627us/step - loss: 0.3379 - accuracy: 0.8629
Epoch 85/100
250/250 [==============================] - 0s 635us/step - loss: 0.3378 - accuracy: 0.8625
Epoch 86/100
250/250 [==============================] - 0s 605us/step - loss: 0.3378 - accuracy: 0.8629
Epoch 87/100
250/250 [==============================] - 0s 841us/step - loss: 0.3376 - accuracy: 0.8619
Epoch 88/100
250/250 [==============================] - 0s 921us/step - loss: 0.3377 - accuracy: 0.8608
Epoch 89/100
250/250 [==============================] - 0s 701us/step - loss: 0.3376 - accuracy: 0.8630
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3377 - accuracy: 0.8633
Epoch 91/100
250/250 [==============================] - 0s 940us/step - loss: 0.3375 - accuracy: 0.8620
Epoch 92/100
250/250 [==============================] - 0s 902us/step - loss: 0.3374 - accuracy: 0.8624
Epoch 93/100
250/250 [==============================] - 0s 927us/step - loss: 0.3376 - accuracy: 0.8635
Epoch 94/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3375 - accuracy: 0.8615
Epoch 95/100
250/250 [==============================] - 0s 904us/step - loss: 0.3375 - accuracy: 0.8630
Epoch 96/100
250/250 [==============================] - 0s 643us/step - loss: 0.3375 - accuracy: 0.8627
Epoch 97/100
250/250 [==============================] - 0s 909us/step - loss: 0.3374 - accuracy: 0.8626
Epoch 98/100
250/250 [==============================] - 0s 673us/step - loss: 0.3373 - accuracy: 0.8629
Epoch 99/100
250/250 [==============================] - 0s 841us/step - loss: 0.3373 - accuracy: 0.8631
Epoch 100/100
250/250 [==============================] - 0s 877us/step - loss: 0.3372 - accuracy: 0.8631

In [33]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,50000,2,1,1,60000]]) > 0.5)

1/1 [==============================] - 0s 78ms/step

array([[0.16199866]], dtype=float32)

In [43]:
y_pred = ann.predict(X_test)

63/63 [==============================] - 0s 932us/step

In [44]:
y_pred = (y_pred > 0.5)

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[   0, 1595],
       [   0,  405]], dtype=int64)

In [46]:
accuracy_score(y_test, y_pred1)

0.2025